# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "20...80"

  status:
    project:
      default:
        target: 20%  # Match build.sbt coverageMinimumStmtTotal
        threshold: 5%  # Allow 5% drop before failing
    patch:
      default:
        # Patch coverage is informational for infrastructure code
        # that requires external services (S3, databases, etc.)
        informational: true

# Ignore files that require external services for testing
ignore:
  - "src/main/scala/org/llm4s/ragbox/Main.scala"
  - "src/main/scala/org/llm4s/ragbox/routes/StaticRoutes.scala"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
