package org.llm4s.ragbox.model

import java.time.Instant

// ============================================================
// Suggestion Types & Severity
// ============================================================

/**
 * Type of optimization suggestion.
 */
sealed trait SuggestionType {
  def name: String
}

object SuggestionType {
  case object Chunking extends SuggestionType { val name = "chunking" }
  case object Search extends SuggestionType { val name = "search" }
  case object Embedding extends SuggestionType { val name = "embedding" }
  case object Content extends SuggestionType { val name = "content" }

  def fromString(s: String): Option[SuggestionType] = s.toLowerCase match {
    case "chunking" => Some(Chunking)
    case "search" => Some(Search)
    case "embedding" => Some(Embedding)
    case "content" => Some(Content)
    case _ => None
  }

  val all: Seq[SuggestionType] = Seq(Chunking, Search, Embedding, Content)
}

/**
 * Severity level of a suggestion.
 */
sealed trait Severity {
  def name: String
  def priority: Int
}

object Severity {
  case object Critical extends Severity { val name = "critical"; val priority = 1 }
  case object Warning extends Severity { val name = "warning"; val priority = 2 }
  case object Info extends Severity { val name = "info"; val priority = 3 }

  def fromString(s: String): Option[Severity] = s.toLowerCase match {
    case "critical" => Some(Critical)
    case "warning" => Some(Warning)
    case "info" => Some(Info)
    case _ => None
  }
}

// ============================================================
// Suggestion Evidence
// ============================================================

/**
 * Evidence that triggered a suggestion.
 *
 * @param metric The metric name (e.g., "chunks_utilization", "avg_rating")
 * @param currentValue The current value of the metric
 * @param threshold The threshold that was exceeded/not met
 * @param sampleSize Number of queries/documents analyzed
 * @param timeRange Description of the analysis period
 */
final case class SuggestionEvidence(
  metric: String,
  currentValue: Double,
  threshold: Double,
  sampleSize: Int,
  timeRange: String
)

// ============================================================
// Optimization Suggestion
// ============================================================

/**
 * An optimization suggestion generated by the analysis engine.
 *
 * @param id Unique identifier for the suggestion
 * @param suggestionType Category of optimization (chunking, search, embedding, content)
 * @param severity Importance level (critical, warning, info)
 * @param title Short title for the suggestion
 * @param description Detailed explanation of the issue
 * @param collection Optional collection name (None = global suggestion)
 * @param evidence Metrics that triggered this suggestion
 * @param recommendation Specific action to take
 * @param estimatedImpact Expected improvement from applying this suggestion
 * @param currentValue Current configuration/metric value
 * @param suggestedValue Recommended new value
 * @param createdAt When this suggestion was generated
 */
final case class OptimizationSuggestion(
  id: String,
  suggestionType: String,  // "chunking", "search", "embedding", "content"
  severity: String,        // "critical", "warning", "info"
  title: String,
  description: String,
  collection: Option[String],
  evidence: SuggestionEvidence,
  recommendation: String,
  estimatedImpact: String,
  currentValue: Option[String],
  suggestedValue: Option[String],
  createdAt: Instant
)

// ============================================================
// API Response Models
// ============================================================

/**
 * Response containing optimization suggestions.
 *
 * @param suggestions List of optimization suggestions
 * @param analyzedQueries Number of queries analyzed
 * @param analyzedCollections Number of collections analyzed
 * @param analysisTimestamp When the analysis was performed
 */
final case class SuggestionsResponse(
  suggestions: Seq[OptimizationSuggestion],
  analyzedQueries: Int,
  analyzedCollections: Int,
  analysisTimestamp: Instant
)

/**
 * Summary of suggestions by severity.
 */
final case class SuggestionsSummary(
  criticalCount: Int,
  warningCount: Int,
  infoCount: Int,
  total: Int,
  topIssues: Seq[String]
)

// ============================================================
// Internal Analysis Models
// ============================================================

/**
 * Collection metrics for analysis.
 */
final case class CollectionMetrics(
  collection: String,
  queryCount: Int,
  avgLatencyMs: Double,
  avgChunksRetrieved: Double,
  avgChunksUsed: Double,
  avgRating: Option[Double],
  ratedQueryCount: Int,
  zeroResultQueries: Int,
  p95LatencyMs: Int
)

/**
 * Global metrics summary for analysis.
 */
final case class GlobalMetrics(
  totalQueries: Int,
  avgLatencyMs: Double,
  avgChunksRetrieved: Double,
  avgChunksUsed: Double,
  avgRating: Option[Double],
  ratedQueryCount: Int,
  zeroResultQueries: Int,
  p95LatencyMs: Int,
  collectionMetrics: Seq[CollectionMetrics]
)

/**
 * Current configuration snapshot for analysis.
 */
final case class ConfigSnapshot(
  chunkingStrategy: String,
  chunkSize: Int,
  chunkOverlap: Int,
  topK: Int,
  embeddingProvider: String,
  embeddingModel: String
)
